language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - SYMFONY_VERSION="2.8.*" DB=mysql

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load --env=test --fixtures=src/AppBundle/DataFixtures --no-interaction

script:
  - ./vendor/bin/simple-phpunit
