# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: username
        # ui_ldap:
        #     ldap:
        #         service: ldap
        #         base_dn: dc=uiuc,dc=edu
        #         search_dn: "dc=uiuc,dc=edu"
        #         search_password: password
        #         default_roles: ROLE_USER
        #         uid_key: uid

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: default
            logout:
                path: logout
                target: login
            provider: db_provider

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/development, roles: ROLE_SUPER_ADMIN }
        - { path: ^/run, roles: ROLE_SUPER_ADMIN }
        - { path: ^/files/docs, roles: ROLE_SUPER_ADMIN }
        - { path: ^/files/schema, roles: ROLE_SUPER_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:	ROLE_USER
        ROLE_SUPER_ADMIN:	ROLE_ADMIN
