security:
    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: username

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: db_provider
            guard:
                authenticators:
                    - app.token_authenticator

    access_control:
        - { path: ^/, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/admin/super, roles: ROLE_SUPER_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:	ROLE_USER
        ROLE_SUPER_ADMIN:	ROLE_ADMIN
