security:
    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: username

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # form_login:
            #     login_path: login
            #     check_path: login
            #     default_target_path: default
            logout:
                path: logout
                target: login
                handlers: [ app.logout_handler ]
                invalidate_session: false
            provider: db_provider
            guard:
                authenticators:
                    - app.token_authenticator

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:	ROLE_USER
        ROLE_SUPER_ADMIN:	ROLE_ADMIN
