# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    ldap:
        class: Symfony\Component\Ldap\LdapClient
        arguments:
            - ldap.illinois.edu
            - 389
            - 3
            - false
            - true

    app.form.user:
        class: AppBundle\Form\UserType
        arguments: ['@security.token_storage']
        tags:
            - { name: form.type }

    app.file_uploader:
        class: AppBundle\FileUploader
        arguments: ['%image_directory%']

    app.doctrine_animal_listener:
        class: AppBundle\EventListener\AnimalImageUploadListener
        arguments: ['@app.file_uploader']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: preRemove }
