parameters:

services:
    app.form.user:
        class: AppBundle\Form\UserType
        arguments: ['@security.token_storage']
        tags:
            - { name: form.type }

    app.file_uploader:
        class: AppBundle\FileUploader

    app.doctrine_animal_listener:
        class: AppBundle\EventListener\AnimalImageUploadListener
        arguments: ['@app.file_uploader', '%image_directory%']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: preRemove }

    app.doctrine_sound_upload_listener:
        class: AppBundle\EventListener\SoundUploadListener
        arguments: ['@app.file_uploader', '%sound_directory%']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: preRemove }

    app.token_authenticator:
      class: AppBundle\Security\TokenAuthenticator
      arguments: ['@doctrine.orm.entity_manager']

    app.response_listener:
      class: AppBundle\EventListener\ResponseListener
      tags:
        - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    session.handler.pdo:
      class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
      public: false
      arguments:
        - 'mysql:host=%database_host%;dbname=%database_name%'
        - { db_username: '%database_user%', db_password: '%database_password%' }

    twig.extension:
        class: AppBundle\Twig\DoctrineExtension
        arguments:
            doctrine: '@doctrine'
        tags:
            - { name: twig.extension }
